name: prokids0
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Localizations
  flutter_localizations:
    sdk: flutter     
  # Gerenciador de estados
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  # json
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1  
  # Rotas
  go_router: ^7.0.1
  # Back4app
  parse_server_sdk_flutter: ^5.0.1
  # image
  image_picker: ^0.8.6+2
  image_picker_for_web: ^2.1.10
    # pdf
  pdf: ^3.10.1
  printing: ^5.10.4
  # outros
  validatorless: ^1.2.3
  intl: ^0.18.0
  url_launcher: ^6.1.9
  font_awesome_flutter: ^10.4.0
  time_planner: ^0.1.1
  uuid: ^3.0.7
  age_calculator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #build_runner
  build_runner: ^2.4.5
  # riverpod
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  # json
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  
flutter:
  uses-material-design: true
